// Angular_React_Vue/Day16/Practice/Angular/Source/authpractice/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ServiceService } from '../service.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css'],
  providers:[ServiceService]
})
export class LoginComponent implements OnInit {

  constructor(private serv:ServiceService,private routes : Router) { }
  msg: any;
  ngOnInit(): void {
  }
      check(uname:string,p:string){
        var output = this.serv.checkup(uname,p);
        if(output){
          this.routes.navigate(['/dashbord']);

        }else{
          this.msg = "Invalid username or password";
        }
      }
}

<div class="container">
<label class="form-label">UserName</label>
<input type="text" class="form-control" #u1 />
<label class="form-label">Password</label>
<input type="text" class="form-control" #p1 />
<button class="btn btn-primary rounded text-white mt-3" (click)="check(u1.value,p1.value)">Login</button>
<br>
<span class="text-danger ">{{ msg }}</span>
</div>

// Angular_React_Vue/Day3/Assignments/React/Source/assignment/src/Components/Login.jsx
import React, { useState } from 'react';

const Login = () => {
        const[user,setUser] =useState('');
        const [pass,setPass]=useState('');
        const[validate,setValidate] =useState();

        const validation = () =>{
            if((user == "admin") && (pass == "admin")){
                setValidate(true);
            }else{
                setValidate(false);
            }
        };

        return(
            <div>
                <h1 className='mb-3'>Login</h1>
                <div>
                    <label className='form-label'>Username</label>
                    <input type="text" 
                    className='form-control'
                    value={user}
                    onChange={(e)=>setUser(e.target.value)}
                    />

                </div>
                <div>
                    <label className='form-label'>Password</label>
                    <input type="text" 
                    className='form-control'
                    value={pass}
                    onChange={(e)=>setPass(e.target.value)}
                    />

                </div>
                <button className='mt-5 btn btn-primary' onClick={validation}>Log in</button>
                <br />

                {validate != null && (validate?(<label className='mt-3 text-success'>User is Valid</label>):(<label className='mt-3 text-danger'>Invalid User</label>))}
            </div>
        )
}

export default Login;
