// Vue/Day 3/Assignment/Source/binding/src/components/LogIn.vue
<template>

       <div class="ms-4">
        <h1>Login</h1>
        <label>Username : </label>
        <input class="form-control" name="usernm" type="text" v-model="user" > <br>
        <label>Password  :  </label>
        <input class="mt-3  form-control" name="ps" type="text" v-model="pass"><br>
        <button @click="check"  class=" rounded p-1 px-3  text-white bg-success mt-2">Login</button>
        <p class="text-danger mt-3 ms-5">{{res}}</p>
        <p class="text-success ms-5">{{res1}}</p>
        </div>
</template>
<script>
export default {
        data(){
            return{
                user:'',
                pass:'',
                res:'',
                res1:'',
                
            }
        },
        methods:{
            check:function (){
                var exp= 'admin';
               if (this.user == '') {
                this.res = "Enter valid username";
                } else if (this.pass == '') {
                this.res = "Enter valid  password";
                } else if (this.user == exp && (this.pass)==exp) {
                this.res1 = "You are Login succesfully!!"
                this.res="";
                } else {
                this.res = "Enter valid user name or password"
                this.res1="";
                }
                        }
                    }
}

</script>
<style scoped>
      @import "../../node_modules/bootstrap/dist/css/bootstrap.min.css";
</style>

// Angular_React_Vue/Day3/Assignments/React/Source/assignment/src/Components/Login.jsx
import React, { useState } from 'react';

const Login = () => {
        const[user,setUser] =useState('');
        const [pass,setPass]=useState('');
        const[validate,setValidate] =useState();

        const validation = () =>{
            if((user == "admin") && (pass == "admin")){
                setValidate(true);
            }else{
                setValidate(false);
            }
        };

        return(
            <div>
                <h1 className='mb-3'>Login</h1>
                <div>
                    <label className='form-label'>Username</label>
                    <input type="text" 
                    className='form-control'
                    value={user}
                    onChange={(e)=>setUser(e.target.value)}
                    />

                </div>
                <div>
                    <label className='form-label'>Password</label>
                    <input type="text" 
                    className='form-control'
                    value={pass}
                    onChange={(e)=>setPass(e.target.value)}
                    />

                </div>
                <button className='mt-5 btn btn-primary' onClick={validation}>Log in</button>
                <br />

                {validate != null && (validate?(<label className='mt-3 text-success'>User is Valid</label>):(<label className='mt-3 text-danger'>Invalid User</label>))}
            </div>
        )
}

export default Login;
