// Vue/Day 4/Practice/Source/greatereven/src/components/EvEn.vue
<template>
    <div class="ms-4">
        <h3>Check Even Number Between 1 to 100 :</h3>
    <div class="mt-4">
    <h5 v-for="item in result" :key="item">
    <h4 v-if="item%2==0">
        {{item}}
    </h4>
</h5>
 </div>
    <button @click="even" class="text-white rounded mt-3 p-1 mx-2 bg-success">Check</button>
    </div>
</template>
<script>
export default {
    data(){
        return{
            result:[] 
        }
    },
    methods: {
        even:function(){
            for( var i=0;i<=100;i++){
        if( i%2==0){
          this.result.push(i);
        }
    }   
        }
    },
}
</script>
<style scoped>
@import "../../node_modules/bootstrap/dist/css/bootstrap.min.css";
</style>

// React/Day 4/Practice/Source/greatereven/src/components/Even.js
import React, { useState } from 'react';

function Even(){
    const [res, setRes] = useState([])
    const even =()=>{
        for( var i=0;i<=100;i++){
            if( i%2==0){
              res.push(i);
            }
        }   
        setRes(res);
        console.log(res);
    }

    return(
        <div>
          
        <div>
            <button onClick={even} type="submit" className='btn text-white rounded mt-3 p-1 mx-2 bg-success'>Click me</button>
        </div>
        <div>
            <h5>{res}</h5>
        </div>
        </div>
    )
}
export default Even
